/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LemondasRouteImport } from './routes/lemondas'
import { Route as ErtekelesRouteImport } from './routes/ertekeles'
import { Route as AszfRouteImport } from './routes/aszf'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdatkezelesRouteImport } from './routes/adatkezeles'
import { Route as IndexRouteImport } from './routes/index'

const LemondasRoute = LemondasRouteImport.update({
  id: '/lemondas',
  path: '/lemondas',
  getParentRoute: () => rootRouteImport,
} as any)
const ErtekelesRoute = ErtekelesRouteImport.update({
  id: '/ertekeles',
  path: '/ertekeles',
  getParentRoute: () => rootRouteImport,
} as any)
const AszfRoute = AszfRouteImport.update({
  id: '/aszf',
  path: '/aszf',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdatkezelesRoute = AdatkezelesRouteImport.update({
  id: '/adatkezeles',
  path: '/adatkezeles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adatkezeles': typeof AdatkezelesRoute
  '/admin': typeof AdminRoute
  '/aszf': typeof AszfRoute
  '/ertekeles': typeof ErtekelesRoute
  '/lemondas': typeof LemondasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adatkezeles': typeof AdatkezelesRoute
  '/admin': typeof AdminRoute
  '/aszf': typeof AszfRoute
  '/ertekeles': typeof ErtekelesRoute
  '/lemondas': typeof LemondasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adatkezeles': typeof AdatkezelesRoute
  '/admin': typeof AdminRoute
  '/aszf': typeof AszfRoute
  '/ertekeles': typeof ErtekelesRoute
  '/lemondas': typeof LemondasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adatkezeles'
    | '/admin'
    | '/aszf'
    | '/ertekeles'
    | '/lemondas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adatkezeles' | '/admin' | '/aszf' | '/ertekeles' | '/lemondas'
  id:
    | '__root__'
    | '/'
    | '/adatkezeles'
    | '/admin'
    | '/aszf'
    | '/ertekeles'
    | '/lemondas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdatkezelesRoute: typeof AdatkezelesRoute
  AdminRoute: typeof AdminRoute
  AszfRoute: typeof AszfRoute
  ErtekelesRoute: typeof ErtekelesRoute
  LemondasRoute: typeof LemondasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lemondas': {
      id: '/lemondas'
      path: '/lemondas'
      fullPath: '/lemondas'
      preLoaderRoute: typeof LemondasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ertekeles': {
      id: '/ertekeles'
      path: '/ertekeles'
      fullPath: '/ertekeles'
      preLoaderRoute: typeof ErtekelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aszf': {
      id: '/aszf'
      path: '/aszf'
      fullPath: '/aszf'
      preLoaderRoute: typeof AszfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adatkezeles': {
      id: '/adatkezeles'
      path: '/adatkezeles'
      fullPath: '/adatkezeles'
      preLoaderRoute: typeof AdatkezelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdatkezelesRoute: AdatkezelesRoute,
  AdminRoute: AdminRoute,
  AszfRoute: AszfRoute,
  ErtekelesRoute: ErtekelesRoute,
  LemondasRoute: LemondasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
